ALTER TABLE messages
    ADD COLUMN rich_content TEXT;

CREATE TABLE message_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversation_id BIGINT NOT NULL,
    uploader_id BIGINT NOT NULL,
    message_id BIGINT NULL,
    original_filename VARCHAR(255),
    stored_filename VARCHAR(255),
    content_type VARCHAR(255),
    size_bytes BIGINT,
    file_path VARCHAR(512),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_message_attachment_conversation FOREIGN KEY (conversation_id) REFERENCES conversations(id),
    CONSTRAINT fk_message_attachment_uploader FOREIGN KEY (uploader_id) REFERENCES users(id),
    CONSTRAINT fk_message_attachment_message FOREIGN KEY (message_id) REFERENCES messages(id) ON DELETE SET NULL
);

CREATE INDEX idx_message_attachments_conversation ON message_attachments(conversation_id);
CREATE INDEX idx_message_attachments_message ON message_attachments(message_id);


